# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_rental_from', models.IntegerField()),
                ('count_rental_to', models.IntegerField()),
                ('percentaje_discount', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
