# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20180116_2201'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_type',
        ),
        migrations.AddField(
            model_name='bikerental',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Rental'),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='rental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.RentalType'),
        ),
    ]
