# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180116_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.Promotion'),
        ),
    ]
