# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 03:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20180117_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 17, 3, 6, 25, 777419, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
