# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
