# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bike_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('ROAD', 'Road'), ('MOUNTAIN', 'Mountain'), ('TRAVEL', 'Travel'), ('ELECTRIC', 'Electric')], default='TRAVEL', max_length=10),
        ),
    ]
