# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
