# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_code', models.CharField(max_length=80)),
                ('bike_type', models.CharField(choices=[('RD', 'Road'), ('MT', 'Mountain'), ('TR', 'Travel'), ('EL', 'Electric')], default='TR', max_length=2)),
            ],
        ),
    ]
